---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-kv2
spec:
  selector:
    matchLabels:
      kubernetes.io/hostname: k8s-worker2
  running: True
  template:
    metadata:
      labels:
        kubevirt.io/vm: ubuntu-kv2
    spec:
      domain:
        cpu:
          sockets: 1
          cores: 6
          threads: 1
        resources:
          requests:
            memory: "16Gi"
            cpu: "6"
          limits:
            cpu: "6"
            memory: "16Gi"
            #memory:
            #  hugepages:
            #    pageSize: "Gi"
        devices:
          disks:
            - name: boot
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
            - name: intf1
              bridge: {}
              model: virtio
            - name: intf3
              bridge: {}
              model: virtio
      volumes:
        - name: boot
          dataVolume:
            name: dv-ubuntu2
      networks:
        - name: default
          pod: {}
        - name: intf1
          multus:
            networkName: intf1
        - name: intf3
          multus:
            networkName: intf3
