apiVersion: core.contrail.juniper.net/v3
kind: Subnet
metadata:
  name: mgmt-v4
  namespace: vsrx
spec:
  cidr: 192.168.5.0/24
  defaultGateway: 192.168.5.1
  enableDhcp: true
  ranges:
  - key: ip-pool-mgmt
    ipRange:
    - from: 192.168.5.2
      to: 192.168.5.100
---
apiVersion: core.contrail.juniper.net/v3
kind: VirtualNetwork
metadata:
  namespace: vsrx
  labels:
    vn: mgmt
spec:
  fabricSNAT: false
  v4SubnetReference:
    apiVersion: core.contrail.juniper.net/v1alpha1
    kind: Subnet
    namespace: vsrx
    name: mgmt-v4
  virtualNetworkProperties:
    forwardingMode: l2_l3
    rpf: enable
