apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: intf2
spec:
  config: '{
    "cniVersion": "0.3.0",
    "name": "intf2",
    "type": "bridge",
    "bridge": "br2",
    "isGateway": true,
    "mtu": 9198,
    "ipam": {
     "type": "host-local",
     "subnet": "192.168.8.0/24"
    }
}'
