apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jcnr-l3-1
spec:
  storageClassName: hostpath-provisioner
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 150Gi
  hostPath:
    path: /opt/aprabh/kubevirt/ubuntu/pv-jcnr-l3-1

