apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: left
  namespace: vsrx
  annotations:
    juniper.net/networks: '{
      "ipamV4Subnet": "192.168.6.0/24"
    }'
  labels:
    vn: vn-left
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "left",
    "type": "contrail-k8s-cni"
  }'
