apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: net-master
spec:
  config: '{
    "cniVersion":"0.4.0",
    "name": "net-master",
    "type": "jcnr",
    "kubeConfig":"/etc/kubernetes/kubelet.conf"
  }'
