apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: net-untrust
spec:
  config: '{
    "cniVersion":"0.4.0",
    "name": "net-untrust",
    "type": "jcnr",
    "args": {
      "vrfName": "untrust",
      "vrfTarget": "10:10"
    },
    "kubeConfig":"/etc/kubernetes/kubelet.conf"
  }'
