apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: l3-intf21
spec:
  config: '{
    "cniVersion": "0.3.0",
    "name": "l3-intf21",
    "type": "bridge",
    "bridge": "l32br21",
    "isGateway": true,
    "mtu":9198,
    "ipam": {
     "type": "host-local",
     "subnet": "192.170.2.0/28"
    }
}'
