apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-u1
spec:
  storageClassName: hostpath-provisioner
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  hostPath:
    path: /opt/aprabh/kubevirt/ubuntu/pv-u1
