apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriovnet-fxp
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_netdevice
spec:
  config: '{
  "type": "sriov",
  "cniVersion": "0.3.1",
  "name": "sriovnet-fxp",
  "ipam": {
    "type": "host-local",
    "subnet": "1.10.1.0/24",
    "routes": [{
      "dst": "0.0.0.0/0"
    }],
    "gateway": "1.10.1.1"
  }
}'
