---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vsrx-cloudinit
  namespace: vsrx
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: vsrx-cloudinit
      annotations:
        k8s.v1.cni.cncf.io/networks: |-
          [
            {
              "name":"mgmt",
              "namespace":"vsrx",
              "cni-args":null,
              "interface":"ge-0/0/0"
            },
            {
              "name":"left",
              "namespace":"vsrx",
              "cni-args":null,
              "interface":"ge-0/0/1"
            },
            {
              "name":"right",
              "namespace":"vsrx",
              "cni-args":null,
              "interface":"ge-0/0/2"
            }
          ]
    spec:
      domain:
        ioThreadsPolicy: auto
        cpu:
          sockets: 1
          cores: 4
          threads: 1
        resources:
          requests:
            memory: 8Gi
            cpu: "4"
          limits:
            cpu: "4"
            memory: 8Gi
        devices:
          useVirtioTransitional: true
          disks:
            - name: containerdisk
              disk: {}
          interfaces:
            - name: default
              masquerade: {}
            - name: mgmt
              bridge: {}
            - name: left
              bridge: {}
            - name: right
              bridge: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: vmidisks/vsrx3:22.4R1.10
      networks:
        - name: default
          pod: {}
        - name: mgmt
          multus:
            networkName: mgmt
        - name: left
          multus:
            networkName: left
        - name: right
          multus:
            networkName: right