apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: k8s-l3-intf1
spec:
  config: '{
    "cniVersion": "0.3.0",
    "name": "k8s-l3-intf1",
    "type": "bridge",
    "bridge": "k8s-l3br1",
    "isGateway": true,
    "mtu":9198,
    "ipam": {
     "type": "host-device",
     "subnet": "192.169.1.0/28"
    }
}'
