---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-kv1
spec:
  running: True
  template:
    metadata:
      labels:
        kubevirt.io/vm: ubuntu-kv1
    spec:
      domain:
        cpu:
          sockets: 1
          cores: 4
          threads: 1
        resources:
          requests:
            memory: 8Gi
            cpu: "4"
          limits:
            cpu: "4"
            memory: 8Gi
        devices:
          disks:
            - name: boot
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
              model: virtio
            - name: fxp
              bridge: {}
            - name: intf1
              bridge: {}
            - name: intf2
              bridge: {}
      volumes:
        - name: boot
          dataVolume:
            name: dv-ubuntu1
      networks:
        - name: default
          pod: {}
        - name: fxp
          multus:
            networkName: fxp
        - name: intf1
          multus:
            networkName: intf1
        - name: intf2
          multus:
            networkName: intf2
