apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: vsrx-boot
spec:
  source:
      upload: {}
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 25Gi 
