apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
spec:
  storageClassName: hostpath-provisioner
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 25Gi
  hostPath:
    path: /root/vsrx-kubevirt/pvdata2
